// <auto-generated />
using System;
using CatalogoWebApp.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CatalogoWebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201123034745_AddDataSeeder")]
    partial class AddDataSeeder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CatalogoWebApp.Models.Autor", b =>
                {
                    b.Property<int>("AutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AutorId");

                    b.HasIndex("CarreraId");

                    b.ToTable("Autores");

                    b.HasData(
                        new
                        {
                            AutorId = 3,
                            Apellidos = "Castillo Ramos",
                            CarreraId = 30,
                            Codigo = "2000-CR-602",
                            Nombres = "Karla Iliana"
                        },
                        new
                        {
                            AutorId = 4,
                            Apellidos = "Gonzalez Velasquez",
                            CarreraId = 29,
                            Codigo = "1995-GV-401",
                            Nombres = "Marco Tulio"
                        },
                        new
                        {
                            AutorId = 5,
                            Apellidos = "Vega Dueñas",
                            CarreraId = 10,
                            Codigo = "2011-VD-101",
                            Nombres = "Joel Ernesto"
                        },
                        new
                        {
                            AutorId = 6,
                            Apellidos = "Torres Gonzalez",
                            CarreraId = 34,
                            Codigo = "1998-TG-601",
                            Nombres = "Mario Ernesto"
                        },
                        new
                        {
                            AutorId = 7,
                            Apellidos = "Calderon Sarmiento",
                            CarreraId = 26,
                            Codigo = "1999-CS-302",
                            Nombres = "Keveen Manolo"
                        },
                        new
                        {
                            AutorId = 8,
                            Apellidos = "Rivas Ascencio",
                            CarreraId = 6,
                            Codigo = "2014-RA-502",
                            Nombres = "Sonia Irene"
                        },
                        new
                        {
                            AutorId = 9,
                            Apellidos = "Sermeño Ortiz",
                            CarreraId = 42,
                            Codigo = "2012-SO-801",
                            Nombres = "Karla Isamar"
                        },
                        new
                        {
                            AutorId = 10,
                            Apellidos = "Salguero",
                            CarreraId = 30,
                            Codigo = "1996-SS-602",
                            Nombres = "Manrique Alonso"
                        },
                        new
                        {
                            AutorId = 11,
                            Apellidos = "Martinez Godinez",
                            CarreraId = 30,
                            Codigo = "2005-MG-605",
                            Nombres = "Mario Ademir"
                        },
                        new
                        {
                            AutorId = 12,
                            Apellidos = "Aguilar Moran",
                            CarreraId = 20,
                            Codigo = "2012-AM-102",
                            Nombres = "Juan Ramon"
                        },
                        new
                        {
                            AutorId = 13,
                            Apellidos = "Miranda",
                            CarreraId = 31,
                            Codigo = "2005-MM-610",
                            Nombres = "Jimmy Patricia"
                        },
                        new
                        {
                            AutorId = 14,
                            Apellidos = "Roman Ortiz",
                            CarreraId = 26,
                            Codigo = "2014-RO-102",
                            Nombres = "Erika Magaly"
                        },
                        new
                        {
                            AutorId = 15,
                            Apellidos = "Perez Moran",
                            CarreraId = 34,
                            Codigo = "2002-PM-603",
                            Nombres = "Denice Beatriz"
                        },
                        new
                        {
                            AutorId = 16,
                            Apellidos = "Trinidad Espino",
                            CarreraId = 14,
                            Codigo = "2006-TE-101",
                            Nombres = "Xinia Liliana"
                        },
                        new
                        {
                            AutorId = 17,
                            Apellidos = "Sandoval Alvarado",
                            CarreraId = 26,
                            Codigo = "2006-SA-302",
                            Nombres = "Ana Vilma"
                        },
                        new
                        {
                            AutorId = 18,
                            Apellidos = "España Canalez",
                            CarreraId = 34,
                            Codigo = "2005-EC-603",
                            Nombres = "Glenda Maritza"
                        },
                        new
                        {
                            AutorId = 19,
                            Apellidos = "Cabrera Orantes",
                            CarreraId = 14,
                            Codigo = "2004-CO-101",
                            Nombres = "Kenia Magdalena"
                        },
                        new
                        {
                            AutorId = 20,
                            Apellidos = "Escobar Hernandez",
                            CarreraId = 5,
                            Codigo = "2007-EH-101",
                            Nombres = "Manuel Gonzalo"
                        },
                        new
                        {
                            AutorId = 21,
                            Apellidos = "Martinez Arce",
                            CarreraId = 40,
                            Codigo = "2000-MA-802",
                            Nombres = "Maria Emilia"
                        },
                        new
                        {
                            AutorId = 22,
                            Apellidos = "Chilin Duran",
                            CarreraId = 11,
                            Codigo = "2007-CD-101",
                            Nombres = "Claribel Yasmin"
                        },
                        new
                        {
                            AutorId = 23,
                            Apellidos = "Andaluz Guzman",
                            CarreraId = 30,
                            Codigo = "1994-AG-602",
                            Nombres = "Jose Francisco"
                        },
                        new
                        {
                            AutorId = 24,
                            Apellidos = "Sierra Fuentes",
                            CarreraId = 40,
                            Codigo = "1997-SF-401",
                            Nombres = "Maria Ladys"
                        },
                        new
                        {
                            AutorId = 25,
                            Apellidos = "Alvarado Pintin",
                            CarreraId = 7,
                            Codigo = "2007-AP-103",
                            Nombres = "Jose Alejandro"
                        },
                        new
                        {
                            AutorId = 26,
                            Apellidos = "Melendez Mojica",
                            CarreraId = 13,
                            Codigo = "2005-MM-108",
                            Nombres = "Jose Rainiero"
                        },
                        new
                        {
                            AutorId = 27,
                            Apellidos = "Bolaños Rivas",
                            CarreraId = 30,
                            Codigo = "2005-BR-601",
                            Nombres = "Joseias Armando"
                        },
                        new
                        {
                            AutorId = 28,
                            Apellidos = "Quijano Rodriguez",
                            CarreraId = 26,
                            Codigo = "2014-QR-101",
                            Nombres = "Carlos Ernesto"
                        },
                        new
                        {
                            AutorId = 29,
                            Apellidos = "Lemus Caballero",
                            CarreraId = 5,
                            Codigo = "2005-LC-101",
                            Nombres = "Raquel Esmeralda"
                        },
                        new
                        {
                            AutorId = 30,
                            Apellidos = "Flores Zaldaña",
                            CarreraId = 43,
                            Codigo = "2013-FZ-801",
                            Nombres = "Stephanie Beatriz"
                        },
                        new
                        {
                            AutorId = 31,
                            Apellidos = "Tenas Perez",
                            CarreraId = 41,
                            Codigo = "2012-TP-801",
                            Nombres = "Jose Francisco"
                        },
                        new
                        {
                            AutorId = 32,
                            Apellidos = "Calles Sanchez",
                            CarreraId = 43,
                            Codigo = "2015-CS-804",
                            Nombres = "Elias Vladimir"
                        },
                        new
                        {
                            AutorId = 33,
                            Apellidos = "Jimenez Romero",
                            CarreraId = 10,
                            Codigo = "2008-JR-101",
                            Nombres = "Adriana Margarita"
                        },
                        new
                        {
                            AutorId = 34,
                            Apellidos = "Martinez Lopez",
                            CarreraId = 35,
                            Codigo = "2015-ML-607",
                            Nombres = "William Enrique"
                        },
                        new
                        {
                            AutorId = 35,
                            Apellidos = "Martinez Pineda",
                            CarreraId = 29,
                            Codigo = "2008-MP-802",
                            Nombres = "Adriana Maria"
                        },
                        new
                        {
                            AutorId = 36,
                            Apellidos = "Ramos Acu¥a",
                            CarreraId = 26,
                            Codigo = "1995-RA-301",
                            Nombres = "Hugo Nelson"
                        },
                        new
                        {
                            AutorId = 37,
                            Apellidos = "Cienfuegos Hernandez",
                            CarreraId = 5,
                            Codigo = "2005-CH-101",
                            Nombres = "Jorge Ernesto"
                        },
                        new
                        {
                            AutorId = 38,
                            Apellidos = "Ramirez Santamaria",
                            CarreraId = 16,
                            Codigo = "2016-RS-151",
                            Nombres = "Marcos Alexander"
                        },
                        new
                        {
                            AutorId = 39,
                            Apellidos = "Duran Tobar",
                            CarreraId = 5,
                            Codigo = "2009-DT-101",
                            Nombres = "Joselin Yanira"
                        },
                        new
                        {
                            AutorId = 40,
                            Apellidos = "Orellana Recinos",
                            CarreraId = 34,
                            Codigo = "2005-OR-601",
                            Nombres = "Marvin Ernesto"
                        },
                        new
                        {
                            AutorId = 41,
                            Apellidos = "Mancia Cabrera",
                            CarreraId = 26,
                            Codigo = "2004-MC-302",
                            Nombres = "Claudia Mariela"
                        },
                        new
                        {
                            AutorId = 42,
                            Apellidos = "Herrera Noches",
                            CarreraId = 8,
                            Codigo = "2007-HN-101",
                            Nombres = "Rosa Maria"
                        },
                        new
                        {
                            AutorId = 43,
                            Apellidos = "Perez Orellana",
                            CarreraId = 6,
                            Codigo = "2011-PO-101",
                            Nombres = "Brenda Lizeth"
                        },
                        new
                        {
                            AutorId = 44,
                            Apellidos = "Moreno Rodriguez",
                            CarreraId = 35,
                            Codigo = "1998-MR-202",
                            Nombres = "Julio Eduardo"
                        },
                        new
                        {
                            AutorId = 45,
                            Apellidos = "Chicas",
                            CarreraId = 10,
                            Codigo = "2015-LC-101",
                            Nombres = "Adan Lopez"
                        },
                        new
                        {
                            AutorId = 46,
                            Apellidos = "Barrera Hernandez",
                            CarreraId = 40,
                            Codigo = "1993-BH-801",
                            Nombres = "Carmen Elena"
                        },
                        new
                        {
                            AutorId = 47,
                            Apellidos = "Mancia Abrego De Esquivel",
                            CarreraId = 26,
                            Codigo = "2006-ME-303",
                            Nombres = "Lili Patricia"
                        },
                        new
                        {
                            AutorId = 48,
                            Apellidos = "Caballero Vidal",
                            CarreraId = 29,
                            Codigo = "2009-CV-801",
                            Nombres = "Veronica Yaneth"
                        },
                        new
                        {
                            AutorId = 49,
                            Apellidos = "Guzman Moran",
                            CarreraId = 40,
                            Codigo = "1993-GM-802",
                            Nombres = "Juan Carlos"
                        },
                        new
                        {
                            AutorId = 50,
                            Apellidos = "Cruz Hernandez",
                            CarreraId = 26,
                            Codigo = "1995-CH-301",
                            Nombres = "Levy Davina"
                        },
                        new
                        {
                            AutorId = 51,
                            Apellidos = "Pop Teni",
                            CarreraId = 13,
                            Codigo = "2016-PT-151",
                            Nombres = "Jefferson Oswaldo"
                        },
                        new
                        {
                            AutorId = 52,
                            Apellidos = "Dueñas Marroquin",
                            CarreraId = 34,
                            Codigo = "1999-DM-601",
                            Nombres = "Idalia Elizabeth"
                        },
                        new
                        {
                            AutorId = 53,
                            Apellidos = "Marquez Beltran",
                            CarreraId = 29,
                            Codigo = "1989-MB-402",
                            Nombres = "Sandra Lissette"
                        },
                        new
                        {
                            AutorId = 54,
                            Apellidos = "Castro Muñoz",
                            CarreraId = 13,
                            Codigo = "2004-CM-101",
                            Nombres = "Julio Ruben"
                        },
                        new
                        {
                            AutorId = 55,
                            Apellidos = "Sicilia Avila",
                            CarreraId = 26,
                            Codigo = "1999-SA-301",
                            Nombres = "Gustavo Antonio"
                        },
                        new
                        {
                            AutorId = 56,
                            Apellidos = "Garcia Mendez",
                            CarreraId = 26,
                            Codigo = "1996-GM-301",
                            Nombres = "Rebeca Fernandina"
                        },
                        new
                        {
                            AutorId = 57,
                            Apellidos = "Mejia Zeceña",
                            CarreraId = 6,
                            Codigo = "2009-MZ-102",
                            Nombres = "Karla Veronica"
                        },
                        new
                        {
                            AutorId = 58,
                            Apellidos = "Garcia Medina",
                            CarreraId = 11,
                            Codigo = "2009-GM-107",
                            Nombres = "Maritza Janeth"
                        },
                        new
                        {
                            AutorId = 59,
                            Apellidos = "Acuña Sandoval",
                            CarreraId = 31,
                            Codigo = "2000-AS-602",
                            Nombres = "Miguel Enrique"
                        },
                        new
                        {
                            AutorId = 60,
                            Apellidos = "Paz Romero",
                            CarreraId = 40,
                            Codigo = "2005-PR-803",
                            Nombres = "Jorge Alberto"
                        },
                        new
                        {
                            AutorId = 61,
                            Apellidos = "Alabi Quinteros",
                            CarreraId = 34,
                            Codigo = "2000-AQ-604",
                            Nombres = "Taufick Salvador"
                        },
                        new
                        {
                            AutorId = 62,
                            Apellidos = "Aguilar Peñate",
                            CarreraId = 30,
                            Codigo = "2001-AP-602",
                            Nombres = "Alvaro Ernesto"
                        },
                        new
                        {
                            AutorId = 63,
                            Apellidos = "Bonilla Portillo",
                            CarreraId = 40,
                            Codigo = "1997-BP-801",
                            Nombres = "Maria Ofelia"
                        },
                        new
                        {
                            AutorId = 64,
                            Apellidos = "Aviles De Perez",
                            CarreraId = 9,
                            Codigo = "2014-AP-502",
                            Nombres = "Liliana Beatriz"
                        },
                        new
                        {
                            AutorId = 65,
                            Apellidos = "Lopez Vasquez",
                            CarreraId = 10,
                            Codigo = "2015-LV-101",
                            Nombres = "Jacqueline Guadalupe"
                        },
                        new
                        {
                            AutorId = 66,
                            Apellidos = "Martinez Orellana",
                            CarreraId = 34,
                            Codigo = "2015-MO-601",
                            Nombres = "William Alexander"
                        },
                        new
                        {
                            AutorId = 67,
                            Apellidos = "Burgos Garcia De Lopez",
                            CarreraId = 11,
                            Codigo = "2000-BL-101",
                            Nombres = "Daysi Eugenia"
                        },
                        new
                        {
                            AutorId = 68,
                            Apellidos = "Ramos Perez",
                            CarreraId = 30,
                            Codigo = "2013-RP-601",
                            Nombres = "Rene Antonio"
                        },
                        new
                        {
                            AutorId = 69,
                            Apellidos = "Molina Luna",
                            CarreraId = 42,
                            Codigo = "2015-ML-802",
                            Nombres = "Jorge Armando"
                        },
                        new
                        {
                            AutorId = 70,
                            Apellidos = "Gonzalez Magaña",
                            CarreraId = 34,
                            Codigo = "2013-GM-603",
                            Nombres = "Francisco Gerardo"
                        },
                        new
                        {
                            AutorId = 71,
                            Apellidos = "Mendoza Flores",
                            CarreraId = 40,
                            Codigo = "1999-MF-801",
                            Nombres = "Dinora Carolina"
                        },
                        new
                        {
                            AutorId = 72,
                            Apellidos = "Lopez Fuentes",
                            CarreraId = 26,
                            Codigo = "1998-LF-802",
                            Nombres = "Dalila Lissette"
                        },
                        new
                        {
                            AutorId = 73,
                            Apellidos = "Martinez",
                            CarreraId = 30,
                            Codigo = "1999-CM-607",
                            Nombres = "Camilo Canizalez"
                        },
                        new
                        {
                            AutorId = 74,
                            Apellidos = "Majico Blanco",
                            CarreraId = 5,
                            Codigo = "2007-MB-103",
                            Nombres = "Gustavo Adolfo"
                        },
                        new
                        {
                            AutorId = 75,
                            Apellidos = "Guzman Rosales",
                            CarreraId = 15,
                            Codigo = "2014-GR-104",
                            Nombres = "Tatiana Maribel"
                        },
                        new
                        {
                            AutorId = 76,
                            Apellidos = "Chavez Sandoval",
                            CarreraId = 31,
                            Codigo = "1998-CS-601",
                            Nombres = "Helen Jeamileth"
                        },
                        new
                        {
                            AutorId = 77,
                            Apellidos = "Cañas Velasquez",
                            CarreraId = 29,
                            Codigo = "2000-CV-802",
                            Nombres = "Brenda Maria"
                        },
                        new
                        {
                            AutorId = 78,
                            Apellidos = "Santana Quintanilla",
                            CarreraId = 30,
                            Codigo = "2013-SQ-601",
                            Nombres = "Sandra Karina"
                        },
                        new
                        {
                            AutorId = 79,
                            Apellidos = "Leiva",
                            CarreraId = 26,
                            Codigo = "2003-LL-301",
                            Nombres = "Nelson Oliverio"
                        },
                        new
                        {
                            AutorId = 80,
                            Apellidos = "Acu Muñoz",
                            CarreraId = 13,
                            Codigo = "2005-AM-103",
                            Nombres = "Marvin Daniel"
                        },
                        new
                        {
                            AutorId = 81,
                            Apellidos = "Magaña Lopez",
                            CarreraId = 42,
                            Codigo = "2013-ML-803",
                            Nombres = "Jose Mauricio"
                        },
                        new
                        {
                            AutorId = 82,
                            Apellidos = "Soriano Zelaya",
                            CarreraId = 14,
                            Codigo = "2006-SZ-101",
                            Nombres = "Evelyn Xiomara"
                        },
                        new
                        {
                            AutorId = 83,
                            Apellidos = "Aragon Romero De Suarez",
                            CarreraId = 20,
                            Codigo = "2012-AS-106",
                            Nombres = "Jancy Magali"
                        },
                        new
                        {
                            AutorId = 84,
                            Apellidos = "Batres De Torres",
                            CarreraId = 6,
                            Codigo = "2005-BB-101",
                            Nombres = "Sandra Rubidia"
                        },
                        new
                        {
                            AutorId = 85,
                            Apellidos = "Turcios Perez",
                            CarreraId = 32,
                            Codigo = "2004-TP-601",
                            Nombres = "Carlos Antonio"
                        },
                        new
                        {
                            AutorId = 86,
                            Apellidos = "Sicilia Molina",
                            CarreraId = 19,
                            Codigo = "2017-SM-151",
                            Nombres = "Manuel Antonio"
                        },
                        new
                        {
                            AutorId = 87,
                            Apellidos = "Espinoza De Paz",
                            CarreraId = 26,
                            Codigo = "2010-ED-301",
                            Nombres = "Jorge Alberto"
                        },
                        new
                        {
                            AutorId = 88,
                            Apellidos = "Guerrero Azucena",
                            CarreraId = 35,
                            Codigo = "1997-GA-202",
                            Nombres = "Jose Mauricio"
                        },
                        new
                        {
                            AutorId = 89,
                            Apellidos = "Cerna Castillo",
                            CarreraId = 41,
                            Codigo = "2012-CC-809",
                            Nombres = "Jenifer Eugenia"
                        },
                        new
                        {
                            AutorId = 90,
                            Apellidos = "Mejia Guevara",
                            CarreraId = 23,
                            Codigo = "2013-MG-109",
                            Nombres = "Eylin Adriana"
                        },
                        new
                        {
                            AutorId = 91,
                            Apellidos = "Serrano Lopez",
                            CarreraId = 8,
                            Codigo = "2008-SL-101",
                            Nombres = "Karla Maria"
                        },
                        new
                        {
                            AutorId = 92,
                            Apellidos = "Montes Fajardo",
                            CarreraId = 34,
                            Codigo = "2008-MF-603",
                            Nombres = "Carlos Raul"
                        },
                        new
                        {
                            AutorId = 93,
                            Apellidos = "Hernandez",
                            CarreraId = 29,
                            Codigo = "2008-HH-801",
                            Nombres = "Henry Arnoldo"
                        },
                        new
                        {
                            AutorId = 94,
                            Apellidos = "Portillo Arbues",
                            CarreraId = 13,
                            Codigo = "2011-PA-103",
                            Nombres = "Jose Amilcar"
                        },
                        new
                        {
                            AutorId = 95,
                            Apellidos = "Yamileth Pineda Peña",
                            CarreraId = 34,
                            Codigo = "2003-PP-601",
                            Nombres = "Rosa Agueda"
                        },
                        new
                        {
                            AutorId = 96,
                            Apellidos = "Avalos Ramos",
                            CarreraId = 31,
                            Codigo = "2012-AR-607",
                            Nombres = "Jose Miguel"
                        },
                        new
                        {
                            AutorId = 97,
                            Apellidos = "Flores Reyes",
                            CarreraId = 32,
                            Codigo = "2008-FR-601",
                            Nombres = "Salvador Alberto"
                        },
                        new
                        {
                            AutorId = 98,
                            Apellidos = "Velasquez Flores",
                            CarreraId = 40,
                            Codigo = "2008-VF-801",
                            Nombres = "Francisco Alfredo"
                        },
                        new
                        {
                            AutorId = 99,
                            Apellidos = "Sandoval Ramirez",
                            CarreraId = 10,
                            Codigo = "2010-SR-101",
                            Nombres = "Luis Miguel"
                        },
                        new
                        {
                            AutorId = 100,
                            Apellidos = "Mejia Aguilar",
                            CarreraId = 8,
                            Codigo = "2008-MA-104",
                            Nombres = "Marvin Alfonso"
                        },
                        new
                        {
                            AutorId = 101,
                            Apellidos = "Marroquin Chavez",
                            CarreraId = 42,
                            Codigo = "2013-MC-806",
                            Nombres = "Ronald Edgardo"
                        },
                        new
                        {
                            AutorId = 102,
                            Apellidos = "Gomez Barrera",
                            CarreraId = 40,
                            Codigo = "1998-GB-801",
                            Nombres = "Jazmin Lissette"
                        },
                        new
                        {
                            AutorId = 103,
                            Apellidos = "Mejia Artero",
                            CarreraId = 14,
                            Codigo = "2005-MA-105",
                            Nombres = "Karla Patricia"
                        },
                        new
                        {
                            AutorId = 104,
                            Apellidos = "Moran Mejia",
                            CarreraId = 8,
                            Codigo = "2007-MM-107",
                            Nombres = "Diana Rebeca"
                        },
                        new
                        {
                            AutorId = 105,
                            Apellidos = "Anaya Marin",
                            CarreraId = 40,
                            Codigo = "2000-AM-801",
                            Nombres = "Veronica Marisol"
                        },
                        new
                        {
                            AutorId = 106,
                            Apellidos = "Alvarez Nolasco",
                            CarreraId = 34,
                            Codigo = "2001-AN-601",
                            Nombres = "Karen Yesenia"
                        },
                        new
                        {
                            AutorId = 107,
                            Apellidos = "Guerra Polanco",
                            CarreraId = 6,
                            Codigo = "2006-GP-102",
                            Nombres = "Elvia Gabriela"
                        },
                        new
                        {
                            AutorId = 108,
                            Apellidos = "Velasquez Paez",
                            CarreraId = 5,
                            Codigo = "2014-VP-104",
                            Nombres = "Yolanda Maria"
                        },
                        new
                        {
                            AutorId = 109,
                            Apellidos = "Vides Garcia",
                            CarreraId = 31,
                            Codigo = "2013-VG-602",
                            Nombres = "Israel Jose"
                        },
                        new
                        {
                            AutorId = 110,
                            Apellidos = "Urquiza Henriquez",
                            CarreraId = 40,
                            Codigo = "2013-UH-801",
                            Nombres = "Christian Francisco"
                        },
                        new
                        {
                            AutorId = 111,
                            Apellidos = "Qui¤onez Marroquin",
                            CarreraId = 30,
                            Codigo = "1997-QM-601",
                            Nombres = "Jose Alfredo"
                        },
                        new
                        {
                            AutorId = 112,
                            Apellidos = "Valencia Castro",
                            CarreraId = 6,
                            Codigo = "2014-VC-501",
                            Nombres = "Brenda Carolina"
                        },
                        new
                        {
                            AutorId = 113,
                            Apellidos = "Paredes Damean",
                            CarreraId = 34,
                            Codigo = "2011-PD-601",
                            Nombres = "Julio Alfonso"
                        },
                        new
                        {
                            AutorId = 114,
                            Apellidos = "Castro Cordova",
                            CarreraId = 40,
                            Codigo = "2004-CC-801",
                            Nombres = "Roxana Carolina"
                        },
                        new
                        {
                            AutorId = 115,
                            Apellidos = "Soto Carranza",
                            CarreraId = 42,
                            Codigo = "2015-SC-806",
                            Nombres = "Roberto Jose"
                        },
                        new
                        {
                            AutorId = 116,
                            Apellidos = "Guerra Henriquez",
                            CarreraId = 29,
                            Codigo = "1999-GH-401",
                            Nombres = "Claudia Maricely"
                        },
                        new
                        {
                            AutorId = 117,
                            Apellidos = "Ortiz Pineda",
                            CarreraId = 43,
                            Codigo = "2000-OP-801",
                            Nombres = "Walter Isaac"
                        },
                        new
                        {
                            AutorId = 118,
                            Apellidos = "Linares Arevalo",
                            CarreraId = 32,
                            Codigo = "2011-LA-602",
                            Nombres = "Mauricio Oswaldo"
                        },
                        new
                        {
                            AutorId = 119,
                            Apellidos = "Galan Morales",
                            CarreraId = 33,
                            Codigo = "1999-GM-603",
                            Nombres = "Josue Elias"
                        },
                        new
                        {
                            AutorId = 120,
                            Apellidos = "Larin Nuñez",
                            CarreraId = 40,
                            Codigo = "1997-LN-501",
                            Nombres = "Douglas Eduardo"
                        },
                        new
                        {
                            AutorId = 121,
                            Apellidos = "Santos Romero",
                            CarreraId = 8,
                            Codigo = "2009-SR-101",
                            Nombres = "Elfida Elisa"
                        },
                        new
                        {
                            AutorId = 122,
                            Apellidos = "Rivera Quijano",
                            CarreraId = 43,
                            Codigo = "2002-RQ-801",
                            Nombres = "Celia Areli"
                        },
                        new
                        {
                            AutorId = 123,
                            Apellidos = "Segura Dolores",
                            CarreraId = 10,
                            Codigo = "2009-SD-101",
                            Nombres = "Idvin Israel"
                        },
                        new
                        {
                            AutorId = 124,
                            Apellidos = "Orantes Lopez",
                            CarreraId = 8,
                            Codigo = "2014-OL-101",
                            Nombres = "Patricia Guadalupe"
                        },
                        new
                        {
                            AutorId = 125,
                            Apellidos = "Barrera",
                            CarreraId = 40,
                            Codigo = "1997-BB-801",
                            Nombres = "Rosa Armida"
                        },
                        new
                        {
                            AutorId = 126,
                            Apellidos = "Orozco Villa",
                            CarreraId = 34,
                            Codigo = "2012-OV-601",
                            Nombres = "Edgar Francisco"
                        },
                        new
                        {
                            AutorId = 127,
                            Apellidos = "Dina Sanchez Recinos",
                            CarreraId = 16,
                            Codigo = "2010-SR-102",
                            Nombres = "Evila Yaran"
                        },
                        new
                        {
                            AutorId = 128,
                            Apellidos = "Moran Campos",
                            CarreraId = 34,
                            Codigo = "1999-MC-605",
                            Nombres = "Billie Vladimir"
                        },
                        new
                        {
                            AutorId = 129,
                            Apellidos = "Agreda Ortiz",
                            CarreraId = 13,
                            Codigo = "2008-AO-101",
                            Nombres = "Alexis Giovanni"
                        },
                        new
                        {
                            AutorId = 130,
                            Apellidos = "Martinez Corleto",
                            CarreraId = 5,
                            Codigo = "2011-MC-101",
                            Nombres = "Gabriela Beatriz"
                        },
                        new
                        {
                            AutorId = 131,
                            Apellidos = "Deleon Palomo",
                            CarreraId = 5,
                            Codigo = "2006-DP-101",
                            Nombres = "Katherine Alexia"
                        },
                        new
                        {
                            AutorId = 132,
                            Apellidos = "Toledo Cea",
                            CarreraId = 30,
                            Codigo = "2014-TC-601",
                            Nombres = "Rene Mauricio"
                        },
                        new
                        {
                            AutorId = 133,
                            Apellidos = "Flores Robles",
                            CarreraId = 32,
                            Codigo = "1999-FR-602",
                            Nombres = "Jose Luis"
                        },
                        new
                        {
                            AutorId = 134,
                            Apellidos = "Herrera Lopez",
                            CarreraId = 13,
                            Codigo = "2012-HL-103",
                            Nombres = "Saul Alonso"
                        },
                        new
                        {
                            AutorId = 135,
                            Apellidos = "Lopez Emestica",
                            CarreraId = 32,
                            Codigo = "2009-LE-601",
                            Nombres = "Efrain Antonio"
                        },
                        new
                        {
                            AutorId = 136,
                            Apellidos = "Salinas Sermeño",
                            CarreraId = 13,
                            Codigo = "2003-SS-101",
                            Nombres = "Francisco Efrain"
                        },
                        new
                        {
                            AutorId = 137,
                            Apellidos = "Hernandez Guerra",
                            CarreraId = 30,
                            Codigo = "1997-HG-601",
                            Nombres = "Iris Marisol"
                        },
                        new
                        {
                            AutorId = 138,
                            Apellidos = "Garrizano Patiño",
                            CarreraId = 6,
                            Codigo = "2008-GP-102",
                            Nombres = "Andrea Patricia"
                        },
                        new
                        {
                            AutorId = 139,
                            Apellidos = "Vasquez Rivera",
                            CarreraId = 35,
                            Codigo = "2015-VR-603",
                            Nombres = "Jose Amilcar"
                        },
                        new
                        {
                            AutorId = 140,
                            Apellidos = "Linares Miranda",
                            CarreraId = 29,
                            Codigo = "2000-LM-801",
                            Nombres = "Tania Ivanova"
                        },
                        new
                        {
                            AutorId = 141,
                            Apellidos = "Lopez Lopez",
                            CarreraId = 35,
                            Codigo = "2013-LL-602",
                            Nombres = "Irmina Veronica"
                        },
                        new
                        {
                            AutorId = 142,
                            Apellidos = "Jesus Escobar Avelar",
                            CarreraId = 34,
                            Codigo = "2004-EA-603",
                            Nombres = "Manuel De"
                        },
                        new
                        {
                            AutorId = 143,
                            Apellidos = "Polanco Guerra",
                            CarreraId = 26,
                            Codigo = "2003-PG-301",
                            Nombres = "Jose Roberto"
                        },
                        new
                        {
                            AutorId = 144,
                            Apellidos = "Rivera Escobar",
                            CarreraId = 29,
                            Codigo = "2004-RE-801",
                            Nombres = "Melvin Jose"
                        },
                        new
                        {
                            AutorId = 145,
                            Apellidos = "Matamoros",
                            CarreraId = 16,
                            Codigo = "2011-MM-105",
                            Nombres = "Katya Jeamileth"
                        },
                        new
                        {
                            AutorId = 146,
                            Apellidos = "Gutierrez Martinez",
                            CarreraId = 43,
                            Codigo = "2012-GM-805",
                            Nombres = "Brenda Seleny"
                        },
                        new
                        {
                            AutorId = 147,
                            Apellidos = "Vanegas Hernandez",
                            CarreraId = 6,
                            Codigo = "2013-VH-101",
                            Nombres = "Katherinne Julissa"
                        },
                        new
                        {
                            AutorId = 148,
                            Apellidos = "Muñoz Leonor",
                            CarreraId = 13,
                            Codigo = "2005-ML-103",
                            Nombres = "William Gustavo"
                        },
                        new
                        {
                            AutorId = 149,
                            Apellidos = "Alvarado Carranza",
                            CarreraId = 9,
                            Codigo = "2017-AC-551",
                            Nombres = "Isabel Estefania"
                        },
                        new
                        {
                            AutorId = 150,
                            Apellidos = "Diaz Chavez",
                            CarreraId = 8,
                            Codigo = "2014-DC-101",
                            Nombres = "Raquel Eunice"
                        },
                        new
                        {
                            AutorId = 151,
                            Apellidos = "Valencia Guerrero De Lemus",
                            CarreraId = 7,
                            Codigo = "2013-VG-102",
                            Nombres = "Claudia Jeanmillette"
                        },
                        new
                        {
                            AutorId = 152,
                            Apellidos = "Chavez Castillo",
                            CarreraId = 34,
                            Codigo = "2005-CC-603",
                            Nombres = "Raul Guillermo"
                        });
                });

            modelBuilder.Entity("CatalogoWebApp.Models.Carrera", b =>
                {
                    b.Property<int>("CarreraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FacultadId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarreraId");

                    b.HasIndex("FacultadId");

                    b.ToTable("Carreras");

                    b.HasData(
                        new
                        {
                            CarreraId = 1,
                            Codigo = "000",
                            FacultadId = 1,
                            Nombre = "GENERAL"
                        },
                        new
                        {
                            CarreraId = 5,
                            Codigo = "101",
                            FacultadId = 100,
                            Nombre = "LICENCIATURA EN PERIODISMO Y COMUNICACIÓN AUDIOVISUAL"
                        },
                        new
                        {
                            CarreraId = 6,
                            Codigo = "102",
                            FacultadId = 500,
                            Nombre = "LICENCIATURA EN ENFERMERIA"
                        },
                        new
                        {
                            CarreraId = 7,
                            Codigo = "103",
                            FacultadId = 500,
                            Nombre = "TECNICO EN ENFERMERIA"
                        },
                        new
                        {
                            CarreraId = 8,
                            Codigo = "104",
                            FacultadId = 100,
                            Nombre = "LICENCIATURA EN CIENCIAS DE LA EDUCACION CON ESPECIALIDAD EN IDIOMA INGLÉS"
                        },
                        new
                        {
                            CarreraId = 9,
                            Codigo = "110",
                            FacultadId = 500,
                            Nombre = "DOCTORADO EN MEDICINA"
                        },
                        new
                        {
                            CarreraId = 10,
                            Codigo = "119",
                            FacultadId = 100,
                            Nombre = "LICENCIATURA EN CIENCIAS DE LA EDUCACION CON ESPECIALIDAD EN EDUCACION BASICA"
                        },
                        new
                        {
                            CarreraId = 11,
                            Codigo = "120",
                            FacultadId = 100,
                            Nombre = "PROFESORADO EN EDUCACION BASICA PARA PRIMERO Y SEGUNDO CICLO"
                        },
                        new
                        {
                            CarreraId = 12,
                            Codigo = "127",
                            FacultadId = 100,
                            Nombre = "PROFESORADO EN EDUCACIÓN PARVULARIA"
                        },
                        new
                        {
                            CarreraId = 13,
                            Codigo = "128",
                            FacultadId = 100,
                            Nombre = "LICENCIATURA EN CIENCIAS RELIGIOSAS"
                        },
                        new
                        {
                            CarreraId = 14,
                            Codigo = "129",
                            FacultadId = 100,
                            Nombre = "LICENCIATURA EN CIENCIAS DE LA EDUCACION CON ESPECIALIDAD EN EDUCACION PARVULARIA"
                        },
                        new
                        {
                            CarreraId = 15,
                            Codigo = "130",
                            FacultadId = 100,
                            Nombre = "LICENCIATURA EN EDUCACION INICIAL Y  PARVULARIA"
                        },
                        new
                        {
                            CarreraId = 16,
                            Codigo = "131",
                            FacultadId = 100,
                            Nombre = "LICENCIATURA EN CIENCIAS DE LA EDUCACION ESPECIALIDAD EN MATEMATICA SEMIPRESENCIAL"
                        },
                        new
                        {
                            CarreraId = 17,
                            Codigo = "132",
                            FacultadId = 100,
                            Nombre = "LICENCIATURA EN CIENCIAS DE LA EDUCACION ESPECIALIDAD EN DIRECCION Y ADMINISTRACION ESCOLAR - SEMIPRESENCIAL"
                        },
                        new
                        {
                            CarreraId = 18,
                            Codigo = "133",
                            FacultadId = 100,
                            Nombre = "LICENCIATURA EN CIENCIAS DE LA EDUCACION ESPECIALIDAD EN EDUCACION BASICA SEMIPRESENCIAL"
                        },
                        new
                        {
                            CarreraId = 19,
                            Codigo = "135",
                            FacultadId = 100,
                            Nombre = "LICENCIATURA EN IDIOMA INGLES (SEMIPRESENCIAL)"
                        },
                        new
                        {
                            CarreraId = 20,
                            Codigo = "140",
                            FacultadId = 100,
                            Nombre = "PROFESORADO EN EDUCACION  BASICA PARA PRIMERO Y SEGUNDO CICLOS"
                        },
                        new
                        {
                            CarreraId = 21,
                            Codigo = "144",
                            FacultadId = 100,
                            Nombre = "PROFESORADO Y LICENCIATURA EN EDUCACION INICIAL Y PARVULARIA"
                        },
                        new
                        {
                            CarreraId = 22,
                            Codigo = "145",
                            FacultadId = 100,
                            Nombre = "LICENCIATURA EN IDIOMA INGLES"
                        },
                        new
                        {
                            CarreraId = 23,
                            Codigo = "160",
                            FacultadId = 100,
                            Nombre = "LICENCIATURA EN DISEÑO GRAFICO PUBLICITARIO"
                        },
                        new
                        {
                            CarreraId = 25,
                            Codigo = "209",
                            FacultadId = 600,
                            Nombre = "INGENIERIA EN TECNOLOGIA Y PROCESAMIENTO DE ALIMENTOS"
                        },
                        new
                        {
                            CarreraId = 26,
                            Codigo = "301",
                            FacultadId = 100,
                            Nombre = "LICENCIATURA EN CIENCIAS JURIDICAS"
                        },
                        new
                        {
                            CarreraId = 29,
                            Codigo = "410",
                            FacultadId = 800,
                            Nombre = "LICENCIATURA EN SISTEMAS INFORMATICOS ADMINISTRATIVOS"
                        },
                        new
                        {
                            CarreraId = 30,
                            Codigo = "601",
                            FacultadId = 600,
                            Nombre = "INGENIERIA INDUSTRIAL"
                        },
                        new
                        {
                            CarreraId = 31,
                            Codigo = "602",
                            FacultadId = 600,
                            Nombre = "ARQUITECTURA"
                        },
                        new
                        {
                            CarreraId = 32,
                            Codigo = "603",
                            FacultadId = 600,
                            Nombre = "INGENIERIA CIVIL"
                        },
                        new
                        {
                            CarreraId = 33,
                            Codigo = "604",
                            FacultadId = 600,
                            Nombre = "INGENIERIA CIVIL SANEAMIENTO AMBIENTAL"
                        },
                        new
                        {
                            CarreraId = 34,
                            Codigo = "605",
                            FacultadId = 600,
                            Nombre = "INGENIERIA EN SISTEMAS INFORMATICOS"
                        },
                        new
                        {
                            CarreraId = 35,
                            Codigo = "606",
                            FacultadId = 600,
                            Nombre = "INGENIERIA AGRONOMICA"
                        },
                        new
                        {
                            CarreraId = 36,
                            Codigo = "607",
                            FacultadId = 600,
                            Nombre = "INGENIERIA EN TELECOMUNICACIONES Y REDES"
                        },
                        new
                        {
                            CarreraId = 37,
                            Codigo = "608",
                            FacultadId = 600,
                            Nombre = "INGENIERIA EN DESARROLLO DE SOFTWARE"
                        },
                        new
                        {
                            CarreraId = 40,
                            Codigo = "801",
                            FacultadId = 800,
                            Nombre = "LICENCIATURA EN ADMINISTRACION DE EMPRESAS"
                        },
                        new
                        {
                            CarreraId = 41,
                            Codigo = "802",
                            FacultadId = 800,
                            Nombre = "LICENCIATURA EN MERCADEO Y NEGOCIOS INTERNACIONALES"
                        },
                        new
                        {
                            CarreraId = 42,
                            Codigo = "803",
                            FacultadId = 800,
                            Nombre = "LICENCIATURA EN GESTION Y DESARROLLO TURISTICO"
                        },
                        new
                        {
                            CarreraId = 43,
                            Codigo = "812",
                            FacultadId = 800,
                            Nombre = "LICENCIATURA EN CONTADURIA PUBLICA"
                        },
                        new
                        {
                            CarreraId = 44,
                            Codigo = "890",
                            FacultadId = 800,
                            Nombre = "POSTGRADO EN ESTRATEGIAS PARA LA COMPETITIVIDAD"
                        },
                        new
                        {
                            CarreraId = 45,
                            Codigo = "900",
                            FacultadId = 900,
                            Nombre = "DEPARTAMENTO DE IDIOMAS"
                        },
                        new
                        {
                            CarreraId = 46,
                            Codigo = "901",
                            FacultadId = 800,
                            Nombre = "MAESTRIA EN DIRECCION ESTRATEGICA DE EMPRESAS"
                        },
                        new
                        {
                            CarreraId = 47,
                            Codigo = "902",
                            FacultadId = 100,
                            Nombre = "MAESTRIA EN ASESORIA EDUCATIVA"
                        },
                        new
                        {
                            CarreraId = 49,
                            Codigo = "904",
                            FacultadId = 100,
                            Nombre = "MAESTRIA EN ATENCION INTEGRAL DE LA PRIMERA INFANCIA"
                        },
                        new
                        {
                            CarreraId = 50,
                            Codigo = "905",
                            FacultadId = 600,
                            Nombre = "MAESTRIA EN GERENCIA Y GESTION AMBIENTAL"
                        },
                        new
                        {
                            CarreraId = 51,
                            Codigo = "906",
                            FacultadId = 800,
                            Nombre = "MAESTRIA EN GESTION Y DESARROLLO TURISTICO"
                        },
                        new
                        {
                            CarreraId = 52,
                            Codigo = "982",
                            FacultadId = 100,
                            Nombre = "CURSO DE FORMACION PEDAGOGICA PARA PROFESIONALES"
                        },
                        new
                        {
                            CarreraId = 56,
                            Codigo = "805",
                            FacultadId = 800,
                            Nombre = "LICENCIATURA EN ADMINISTRACION DE EMPRESAS - SEMIPRESENCIAL"
                        });
                });

            modelBuilder.Entity("CatalogoWebApp.Models.Facultad", b =>
                {
                    b.Property<int>("FacultadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FacultadId");

                    b.ToTable("Facultades");

                    b.HasData(
                        new
                        {
                            FacultadId = 1,
                            Codigo = "NA",
                            Nombre = "NO ASIGNADA"
                        },
                        new
                        {
                            FacultadId = 100,
                            Codigo = "100",
                            Nombre = "CIENCIAS  Y HUMANIDADES"
                        },
                        new
                        {
                            FacultadId = 500,
                            Codigo = "500",
                            Nombre = "FACULTAD DE CIENCIAS DE LA SALUD"
                        },
                        new
                        {
                            FacultadId = 600,
                            Codigo = "600",
                            Nombre = "INGENIERIA Y ARQUITECTURA"
                        },
                        new
                        {
                            FacultadId = 800,
                            Codigo = "800",
                            Nombre = "CIENCIAS EMPRESARIALES"
                        },
                        new
                        {
                            FacultadId = 900,
                            Codigo = "900",
                            Nombre = "DEPARTAMENTO DE IDIOMAS"
                        },
                        new
                        {
                            FacultadId = 906,
                            Nombre = "BIBLIOTECA"
                        });
                });

            modelBuilder.Entity("CatalogoWebApp.Models.Tipo", b =>
                {
                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoId");

                    b.ToTable("Tipos");

                    b.HasData(
                        new
                        {
                            TipoId = 1,
                            Nombre = "Pasantia"
                        },
                        new
                        {
                            TipoId = 2,
                            Nombre = "Proyecto"
                        },
                        new
                        {
                            TipoId = 3,
                            Nombre = "Tesis"
                        });
                });

            modelBuilder.Entity("CatalogoWebApp.Models.TrabajoDeGraduacion", b =>
                {
                    b.Property<int>("TrabajoDeGraduacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("PathImagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrabajoDeGraduacionId");

                    b.HasIndex("AutorId");

                    b.HasIndex("TipoId");

                    b.ToTable("TrabajosDeGraduacion");
                });

            modelBuilder.Entity("CatalogoWebApp.Models.Autor", b =>
                {
                    b.HasOne("CatalogoWebApp.Models.Carrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("CatalogoWebApp.Models.Carrera", b =>
                {
                    b.HasOne("CatalogoWebApp.Models.Facultad", "Facultad")
                        .WithMany("Carreras")
                        .HasForeignKey("FacultadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facultad");
                });

            modelBuilder.Entity("CatalogoWebApp.Models.TrabajoDeGraduacion", b =>
                {
                    b.HasOne("CatalogoWebApp.Models.Autor", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogoWebApp.Models.Tipo", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("CatalogoWebApp.Models.Facultad", b =>
                {
                    b.Navigation("Carreras");
                });
#pragma warning restore 612, 618
        }
    }
}
